### ISSUE TITLE
Issue while using Manual Renewal option

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay-woocommerce#15]
Hello team

If we select the "Accept Manual Renewals" option in Woocommerce Subscription, Woocommerce enables all the payment gateways even if that payment gateway does not support subscription/recurring payments.
I think those payments should not be considered subscription payments. These should consider one-time payments. At the same time, Pronamic Ideal considers these payments as subscription payments. We are getting the "Gateway does not support recurring payments." error in the notes of these payments. I think these payments should work even if the gateway does not support recurring payments and subscriptions should not create in Pronamic Ideal. Correct me if I am wrong.

https://woocommerce.com/document/subscriptions/renewal-process/

![Screenshot 2022-10-11 215103](https://user-images.githubusercontent.com/65900807/195148681-5c1228ed-31dc-4e0b-ab1e-5f25388ad53f.png)

![Screenshot 2022-10-11 215324](https://user-images.githubusercontent.com/65900807/195148673-46a70f24-0bd9-4a24-aa14-5fbd0d3835f4.png)

**Comment by remcotolsma** [comment]
Yes, there is indeed room for improvement. I wonder if we should still throw that exception:

```php
if ( \count( $subscriptions ) > 0 && ! $gateway->supports( 'recurring' ) ) {
	throw new \Exception( 'Gateway does not support recurring payments.' );
}
```

https://github.com/pronamic/wp-pay-core/blob/1afa5d029986ef85024d85622004fe3feeaac158/src/Plugin.php#L1195-L1197

I think we could do without that exception for WooCommerce. In combination with Gravity Forms, we saw that users sometimes set it up incorrectly and therefore incorrectly assumed that follow-up payments would be collected automatically. To cover that we introduced this condition and exception. I will check the other extensions with subscription support:

- **MemberPress**
   - https://github.com/pronamic/wp-pronamic-pay-memberpress/blob/a9ed77a71e2c64ab14e744461661aba8ee08a121/src/Gateways/Gateway.php
   - https://github.com/pronamic/wp-pronamic-pay-memberpress/blob/a9ed77a71e2c64ab14e744461661aba8ee08a121/src/Extension.php
- **Restrict Content Pro**
   - https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/blob/3a531356c0c0b3d0a1f4feed0e058509289d539a/src/Gateway.php
   - https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/blob/3a531356c0c0b3d0a1f4feed0e058509289d539a/src/Extension.php
- **Gravity Forms**
   - https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/563f076e48b730ecdd985369ffbd97285064d7cb/src/Extension.php
   - https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/563f076e48b730ecdd985369ffbd97285064d7cb/src/Processor.php

I think we can move this exception downstream to just the Gravity Forms extension for now.

**Comment by knit-pay** [comment]
Hello @remcotolsma 

I think these 2 are different things. You have mentioned throwing exceptions if the gateway does not support recurring payments.
But in actuality, the WooCommerce Manual Payment feature is something different. It's a normal one-time payment. Using this feature any payment gateway which does not support recurring payment can be used for collecting payment for woocommerce subscriptions. In this case, Woocommerce is handling the subscription process on this own. there is no need to create subscription in wp-pay-core.

**Comment by remcotolsma** [comment]
They are indeed 2 different things, but they are related. The core library should not throw an exception for these manual subscription payments. It's not entirely a normal one-time payment, a WooCommerce manual renewal order (payment) is connected / related to a WooCommerce subscription. For now we will also create a Pronamic Pay subscription for these orders and link the follow-up payments to the subscription.

- https://github.com/pronamic/wp-pay-core/pull/80
- https://github.com/pronamic/wp-pronamic-pay-woocommerce/issues/20

In this way, the extensions can determine whether or not a subscription payment can be initiated at a gateway that does not support recurring payments. For Gravity Forms we will disable this for now, but perhaps we will also add support for manual renewals in the future:

https://github.com/pronamic/wp-pronamic-pay-gravityforms/commit/8a778e4cb59e93ed08b717cc2bfc331bb277f872
