### ISSUE TITLE
€ 0,00 refund triggered on deleting payments

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-woocommerce#31]
It seems that deleting payments can trigger refunds of € 0,00:

<img width="294" alt="Scherm­afbeelding 2022-11-24 om 14 26 22" src="https://user-images.githubusercontent.com/10371164/203795545-9d3689ed-b449-46ff-a3f2-6e7a5fe57933.png">

This seems to be caused by operands of incompatible types (`float` vs `string`):

https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/64fe6c94704f8b31a34c1d41e4778e7be74414b4/src/Extension.php#L762-L769

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2077581202/24843/_

**Comment by rvdsteege** [comment]
@remcotolsma I propose the below change, but find it a bit strange to first cast the meta to `float` and then to `string` — only to end up with string `0` instead of an empty string if there is no `_pronamic_amount_refunded` order meta. Any other ideas? `Money` and `Number` classes do not have a `to_float()` method, otherwise we could maybe use that?

```php
 if ( (string) $wc_refunded_amount === $refunded_value ) {
```

**Comment by remcotolsma** [comment]
Should we introduce a `equals` method in the `Number` class?
https://github.com/pronamic/wp-number/blob/c26538f223ae4326e8758679ed7372020d15b1d1/src/Number.php

A bit like:
https://github.com/moneyphp/money/blob/43580b8a94142ae5db9e4c86c6ecaabea66f27c9/src/Money.php#L109-L127

And/or we should not create a refund if `$amount_difference` is zero?
https://github.com/pronamic/wp-number/blob/c26538f223ae4326e8758679ed7372020d15b1d1/src/Number.php#L186-L196

**Comment by rvdsteege** [comment]
Discussed with @remcotolsma at Pronamic HQ and resolved in https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/2ed4a200ac3c39f02645a362e2d5e97ac843da34.
