### ISSUE TITLE
Update for WooCommerce Subscriptions HPOS

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-woocommerce#32]
> In [WooCommerce Subscriptions](https://woocommerce.com/document/subscriptions/) 4.9.0 we declared compatibility with WooCommerce’s new High-Performance Order Storage (HPOS) feature, which means it’s time for extensions that integrate with WooCommerce Subscriptions to update their code in order to be compatible with Subscriptions being stored in the new wc_orders tables.

https://developer.woocommerce.com/2023/03/07/woocommerce-subscriptions-hpos-understanding-next-steps/

For example, this should be updated:
https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/2ae572d430d558f1ee6e0468b0f73c31fe515777/src/SubscriptionUpdater.php#L189-L192

**Comment by LeoOosterloo** [comment]
Good to know: According to the timeline for HPOS integration:
>2023-08-08: HPOS becomes the default experience for stores with WooCommerce 8.0: data synchronization with posts/postmeta tables will be disabled.

https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/
