### ISSUE TITLE
WooCommerce Subscription renewal order period

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-woocommerce#39]
WooCommerce Subscriptions unfortunately does not keep track of the period for which the renewal order is:

https://github.com/Automattic/woocommerce-subscriptions-core/blob/f2987e24ba5a1e5e564843b96a434596e05cc96c/includes/wcs-renewal-functions.php#L17-L39

In Pronamic Pay, we always linked a subscription period to the Pronamic payment. It now appears that we cannot do this reliably. Therefore, we have removed the related code in: https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/96228ef07331243892d20e827a91756732cc1cb8.

Discussed with @rvdsteege that we might be able to link automatic renewals to a period in the future.

- https://github.com/pronamic/wp-pronamic-pay/issues/201

**Comment by remcotolsma** [comment]
I've investigated this further, but it seems impossible to determine whether a payment was initiated through the action scheduler or through a WordPress admin meta box, as the same routine is called by WooCommerce Subscriptions (`do_action( 'woocommerce_scheduled_subscription_payment', …`). Because WooCommerce Subscriptions itself does not link a period to a renewal order, it seems simpler and better to omit this for now.

```php
	/**
	 * Handles the action request to process a renewal order.
	 *
	 * @param array $subscription
	 * @since 1.0.0 - Migrated from WooCommerce Subscriptions v2.0
	 */
	public static function process_renewal_action_request( $subscription ) {
		$subscription->add_order_note( __( 'Process renewal order action requested by admin.', 'woocommerce-subscriptions' ), false, true );
		do_action( 'woocommerce_scheduled_subscription_payment', $subscription->get_id() );
	}
```

https://github.com/Automattic/woocommerce-subscriptions-core/blob/f2987e24ba5a1e5e564843b96a434596e05cc96c/includes/admin/class-wcs-admin-meta-boxes.php#L236-L245

**Comment by rvdsteege** [comment]
> it seems impossible to determine whether a payment was initiated through the action scheduler or through a WordPress admin meta box […]

Maybe `did_action( 'action_scheduler_begin_execute' )`?

- https://developer.wordpress.org/reference/functions/did_action/
- https://github.com/woocommerce/action-scheduler/blob/1373570a9ee03a0be31c73df086d1e4343a27347/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L43-L88

**Comment by remcotolsma** [comment]
Yes, or maybe https://developer.wordpress.org/reference/functions/wp_doing_cron/, the question is whether such a hacky (?) solution is worth it. I do see that a WooCommerce subscription with next payment date `2024-05-24 @ 12:58` (Amsterdam) has scheduled an Action Scheduler action on `2024-05-24 10:58:58 +0000`. The WooCommerce renewal order created at that time will most likely have a date greater than `2024-05-24 10:58:58 +0000`. If we use `$pronamic_subscription->get_period_for_date( $wc_order->get_date_created() )` not much can go wrong in that regard either. Let's think about this for a moment...

**Comment by rvdsteege** [comment]
> Yes, or maybe https://developer.wordpress.org/reference/functions/wp_doing_cron/

I don't think `wp_doing_cron()` is correct, as processing the actions could have been started through WP-CLI (`wp action-scheduler run`).

I'm always in for hacky solutions 😜 But I'm not sure what to do either, continue thinking... just wanted to mention the above about `wp_doing_cron()`.

**Comment by remcotolsma** [comment]
Hmm yeah, it's not that simple, for now I'm leaning most towards:

> Because WooCommerce Subscriptions itself does not link a period to a renewal order, **it seems simpler and better to omit this for now**.

If we get new insights, we can always revise this.
