### ISSUE TITLE
Customizing the order button text

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-woocommerce#47]
From customer:

> Zodra jullie plugin namelijk ingeladen wordt wordt mijn (huidige tekst, "Bestel en betaal", hier gebruik ik de filter inderdaad voor) vervangen door jullie tekst "Ga verder naar iDEAL". Daar kan ik vervolgens niets mee lijkt het. Ik wil dat het wordt "Ga verder naar iDeal en betaal".

It seems there is no way to customize the order button text of Pronamic Pay gateways. I was under the impression that this could be done with the WooCommerce filter `woocommerce_order_button_text`, but unfortunately that does not seem to be the case.

The filter is called, but the value gets overridden through a HTML attribute `‎data-order_button_text‎` with the value of `$gateway->order_button_text` in the default checkout payment method template:
- https://github.com/woocommerce/woocommerce/blob/957fb2b07e28a414cfaf750df1f5f3a999306de7/plugins/woocommerce/includes/wc-template-functions.php#L2388-L2407
- https://github.com/woocommerce/woocommerce/blob/957fb2b07e28a414cfaf750df1f5f3a999306de7/plugins/woocommerce/templates/checkout/payment-method.php#L23C216-L23C295

Customizing the order button text can be crucial, for example to comply with laws and regulations:

> The order button clearly shows that payment is mandatory when the customer clicks on it. For example, 'Order and pay' or 'Order with payment obligation'. Only 'Order' is not clear enough.
>
> _Source: https://www.acm.nl/nl/verkoop-aan-consumenten/checklist-online-verkoop_

Order button texts:
- WooCommerce default: `Place order`
- Pronamic default: `Proceed to {method}`
- PayPal gateway: `Proceed to PayPal`
- Mollie for WooCommerce plugin: does not set `$gateway->order_button_text`

Suggestions:
1. don't set `$gateway->order_button_text` so that the WooCommerce filter `woocommerce_order_button_text` can be used or;
2. add a gateway setting for the order button text, with fallback to the current `Proceed to {method}`.

Thoughts, @remcotolsma?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2286491623/25824_

**Comment by remcotolsma** [comment]
3. Add a `pronamic_pay_woocommerce_order_button_text` filter?
   https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/ec9bd948d5d9b8e77d4e312a04dbd154b0d28217/src/Gateway.php#L142-L153

**Comment by rvdsteege** [comment]
I left that option out because it would introduce another 'hidden setting' and thought I'd prefer 2️⃣ over 3️⃣, but for translations and consistency in the button text (same format for all payment methods) introducing a filter could be a better option.

The `woocommerce_order_button_text` filter only accepts the button text as parameter. Would it be beneficial to also add a second parameter with the payment method name?

**Comment by remcotolsma** [comment]
We now have a dedicated plugin for this: https://www.pronamic.shop/product/pronamic-woocommerce-gateway-order-button-text-setting/.
