### ISSUE TITLE
Error "Unable to change subscription status to `pending`."

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-woocommerce#48]
Some empty try/catch'es have recently been removed by @remcotolsma (https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/45e08843992f6208d58fb7b6e4b24aa458dddfea and https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/5c4c5098e615f1ba862ba258bf1aa22d005859fb), because it was not clear why they were there.

Thanks to an issue at pronamic.shop, I now discovered that both were there because of the following error message which otherwise prevents payment start when changing the payment method of a subscription:

> Something went wrong with the payment. Please try again or pay another way.
> Unable to change subscription status to "pending".

With the try/cache in place, the error message does not appear and at least the creditcard gateway can be used for payment (other gateways might still result in an error regarding a minimum amount).

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2359765662/26151_

**Comment by remcotolsma** [comment]
This afternoon we already did some research at @pronamic HQ, exception is probably thrown here:
https://github.com/Automattic/woocommerce-subscriptions-core/blob/c212aa302f6b7992199bfed358e712df52ffb17b/includes/class-wc-subscription.php#L422-L435

Only WooCommerce subscriptions with status `draft` and `auto-draft` can be changed to `pending`:
https://github.com/Automattic/woocommerce-subscriptions-core/blob/c212aa302f6b7992199bfed358e712df52ffb17b/includes/class-wc-subscription.php#L314-L328

So the question is why we try to set a WooCommerce subscription status to `pending`. Should we check if the `$order` is actually a WooCommerce subscription instance?
