### ISSUE TITLE
WooCommerce Blocks support?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-woocommerce#9]
Asked by @LeoOosterloo on January 28 in internal Basecamp to-do: https://basecamp.com/1810084/projects/10966871/todos/433577248, does Pronamic Pay support the new WooCommerce Blocks (checkout)? This In response to the following WordPress.org support topic: https://wordpress.org/support/topic/support-for-new-woocommerce-blocks/#post-13967141. And a potential customer also inquired about this in internal HelpScout ticket https://secure.helpscout.net/conversation/1642567772/22782?folderId=1425715.  I also noticed the following topic: https://wordpress.org/support/topic/mollie-doesnt-work-with-woocommerce-blocks/#post-14910778.

> Hi! I'm wondering if there's an update about this. I spent a week finetuning and tweaking my soon to be launched webshop with the new Woocommerce Block layouts for Checkout and Cart - only to realize after this whole week of building, that Blocks doesn't support all payment methods. I looked around, Stripe also doesn't have iDeal support yet in Woocommerce Blocks - would be a lifesaver if Mollie does support iDeal in Woocommerce Blocks!  :-)

https://developer.woocommerce.com/2020/05/27/available-for-testing-a-block-based-woocommerce-cart-and-checkout/

**Comment by rvdsteege** [comment]
Added initial support for WooCommerce Blocks in https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/7b8969d02e38e4f7d503a2f3d06d6b0510b7f868 🎉

<img width="542" alt="Schermafbeelding 2022-03-14 om 15 13 17" src="https://user-images.githubusercontent.com/10371164/158190270-8da42a7f-34e7-4c95-a604-241850c5d3c9.png">

**Comment by remcotolsma** [comment]
@rvdsteege On my local test and develop environment i get hundreds of the following notices:

![pay local_wp-admin_](https://user-images.githubusercontent.com/869674/159707084-dbf336d9-1abf-4107-8623-54e6023c3016.png)

If i remove the following line they are gone:

```php
\add_filter( 'woocommerce_blocks_loaded', array( __CLASS__, 'payment_gateways' ) );
```

https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/7b8969d02e38e4f7d503a2f3d06d6b0510b7f868#diff-6f62438f6bf291e85f644dbdbb14b2a71a9a7ed205b01ce44290ed85abe2aa07R82

I also noticed this change:

https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/7b8969d02e38e4f7d503a2f3d06d6b0510b7f868#diff-6f62438f6bf291e85f644dbdbb14b2a71a9a7ed205b01ce44290ed85abe2aa07R125-R128

Hooking our `array( __CLASS__, 'payment_gateways' )` method into the `woocommerce_blocks_loaded` filter is not the way to go?

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b90dccb92267a5179b4a1f86efa1f3ceff12a4f2/src/Domain/Bootstrap.php#L57-L63

**Comment by rvdsteege** [comment]
Thanks for the feedback, @remcotolsma! Made some changes in https://github.com/pronamic/wp-pronamic-pay-woocommerce/commit/a043c3c9cb6e9da610a92d2ce5184979866eb502, which no longer initializes the gateways on the `woocommerce_blocks_loaded` action.

Does this resolve the notices with WooCommerce Subscriptions for you (I was unable to reproduce these exact notices)?

**Comment by remcotolsma** [comment]
Yes, that fixes it, but I'm still wondering if this is the right way. We now initiate all our gateways to just get access to the `gateway_args`?

```php
	/**
	 * Register blocks payment method type.
	 *
	 * @param PaymentMethodRegistry $payment_method_registry
	 * @return void
	 */
	public function register_blocks_payment_method_type( PaymentMethodRegistry $payment_method_registry ) {
		if ( 'yes' !== $this->enabled ) {
			return;
		}


		$args = \array_merge(
			$this->gateway_args,
			array(
				'name'     => $this->id,
				'supports' => $this->supports,
			)
		);


		$payment_method_type = new PaymentMethodType( $args );


		$payment_method_registry->register( $payment_method_type );
	}
```

Shouldn't we keep this more separate from the classic `Gateway extends WC_Payment_Gateway` class?

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md

Couldn't find any information about the best practices yet:

- https://github.com/woocommerce/woocommerce-paypal-payments/search?q=woocommerce_blocks_loaded
- https://github.com/woocommerce/woocommerce-gateway-stripe/search?q=woocommerce_blocks_loaded

Or have you seen examples of WooCommerce where they do it in a similar way?

Otherwise we might be able to arrange this a little more upstream so that the gateways don't have to be initiated (unnecessarily)?

**Comment by remcotolsma** [comment]
Ok, great, I see the similarities with the PayPal setup. Are we completely there or is there something else that needs to be done?

**Comment by rvdsteege** [comment]
Yesterday, I noticed we don't support input fields yet (e.g. issuer field for iDEAL). As some gateways require the issuer, I think we need to fix this before release (but I'm not sure if we can somehow just use the existing input fields — at least for now — or if this needs to be baked into the JavaScript payment method). I'll have a look at this today.

**Comment by remcotolsma** [comment]
> Yesterday, I noticed we don't support input fields yet (e.g. issuer field for iDEAL). As some gateways require the issuer, I think we need to fix this before release (but I'm not sure if we can somehow just use the existing input fields — at least for now — or if this needs to be baked into the JavaScript payment method). I'll have a look at this today.

Added in https://github.com/pronamic/wp-pronamic-pay-woocommerce/compare/a3ebb5d0e076da0d45c7aa2638a6a4b96ce63480...606b5a5195b57d75291bf67978b6a99f01aa3c11.
